import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Providers from "@/lib/Providers";
import { Toaster } from "sonner";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <Providers>
    <html lang="en" data-theme="light">
      <body>
        <Navbar />
        <div className="min-h-screen w-[90%] mx-auto">
        <>
        <Toaster  position='top-center'/>
           {children}
        </>
          
          </div>
          <Footer/>
      </body>
    </html>
    </Providers>
  );
}
